name: task2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  provider: ^6.0.2
  flutter_hooks: ^0.18.2
  equatable: ^2.0.3
  formz: ^0.4.1
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  flow_builder: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true